### ISSUE TITLE
missing braces

### ISSUE THREAD

**Issue by swsabean** [gkikola/sol-dummit-foote#1]
In the file src/ch00/section2.tex, at line 166 you have
\frac{ab}dt
I am pretty sure that you meant
\frac{ab}{d}t
although it works without the braces. I only mention it because it seems cleaner with the braces included.

Incidentally, I have been going through your solutions, comparing them to what I have done. If you like, I can send up signals whenever I spot errors, typos, etc. I do hope that you continue working on this repository. I would like to see a complete set of solutions to the text.

Regards,
-Steve

**Comment by gkikola** [comment]
Yes, I admit that I am a little lazy with braces in my TeX. Hopefully it isn't too bothersome.

Certainly if you see any errors or typos in the solutions, feel free to let me know. It is appreciated.

And I do intend to continue working on these solutions. I should be adding more very soon.

Thanks for your comment,

Greg Kikola

**Comment by gkikola** [comment]
Fixed
