### ISSUE TITLE
use \overline instead of \bar

### ISSUE THREAD

**Issue by swsabean** [gkikola/sol-dummit-foote#2]
In the file src/ch00/section3.tex at line 43, you have

$\{\bar{0}, \bar{1}, \ldots, \bar{n-1}\}$.

This should be changed to read

$\{\bar{0}, \bar{1}, \ldots, \overline{n-1}\}$.

Regards,
-Steve

**Comment by gkikola** [comment]
Good catch, thanks. I fixed it.
